WebApplication2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using WebApplication2.Models;
using WebApplication2.Services.Interface;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        private IUserInfoService userInfoService;

        public HomeController(IUserInfoService userInfoService)
        {
            this.userInfoService = userInfoService;
        }

        [Authorize]
        public ActionResult Index()
        {
            return RedirectToAction("ViewUser");
        }

        [Authorize]
        public ActionResult ViewUser()
        {
            var userInfoModel = this.userInfoService.GetUserInfoModel(this.GetUserId());
            return View("ViewUser", userInfoModel);
        }

        [Authorize]
        public ActionResult EditUser()
        {
            var userInfoViewModel = this.userInfoService.GetUserInfoForEdit(this.GetUserId());
            return this.View(userInfoViewModel);
        }

        /// <summary>
        /// Получить идентификатор текущего пользователя
        /// </summary>
        /// <returns></returns>
        private Guid GetUserId()
        {
            return new Guid(this.User.Identity.GetUserId());
        }


        [Authorize]
        [HttpPost]
        public ActionResult SaveUser(UserInfoViewModel viewModel)
        {
            this.userInfoService.SaveUserInfo(viewModel);
            return RedirectToAction("EditUser");
        }

        [Authorize]
        [HttpPost]
        public ActionResult CreateUser(UserInfoViewModel viewModel)
        {
            viewModel.UserId = this.GetUserId();
            this.userInfoService.CreateUserInfo(viewModel);
            return RedirectToAction("EditUser");
        }

        [Authorize]
        public ActionResult RemoveFavoriteSinger(int id)
        {
            this.userInfoService.RemoveFavoriteSinger(id, this.GetUserId());

            return new EmptyResult();
        }


        [Authorize]
        public ActionResult AddFavoriteSinger(int id)
        {
            return PartialView("~/Views/Shared/SingerEditView.cshtml", this.userInfoService.AddFavoriteSinger(id, this.GetUserId()));
        }



        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication2/Controllers/SingerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;
using WebApplication2.Services.Interface;

namespace WebApplication2.Controllers
{
    public class SingerController : Controller
    {
        private readonly ISingerService singerService;
        /// <summary>
        /// Initializes a new instance of the <see cref="T:System.Web.Mvc.Controller"/> class.
        /// </summary>
        public SingerController(ISingerService singerService)
        {
            this.singerService = singerService;
        }


        [Authorize]
        public ActionResult AddNewFavoriteSinger()
        {
            return PartialView("SingerCreateView", this.singerService.GetCreateViewModel());
        }

        [Authorize]
        
        public JsonResult CreateNewSinger(int? genreId, string name)
        {
            
            return Json( this.singerService.CreateNewSinger(name, genreId));
        }

        
        public JsonResult GetByGenre(int genreId)
        {
            List<SingerModel> singerByGenre = this.singerService.GetSingerByGenre(genreId);

            return Json(singerByGenre);
        }

    }
}

WebApplication2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication2/Views/Home/EditUser.cshtml
@using RedCore
@using WebApplication2.Models
@model WebApplication2.Models.UserInfoViewModel

@{
    ViewBag.Title = "Просмотр пользователя";
}



<h2>Пользователь</h2>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")


@using (Html.BeginForm(Model == null ? "SaveUser" : "CreateUser", "Home", FormMethod.Post))
{
    @Html.HiddenFor(model => model.UserId)
    <table>
        <tr>
            <td>@Html.DisplayNameFor(model => model.FirstName)</td>
            <td>@Html.EditorFor(model => model.FirstName)</td>
            <td>@Html.ValidationMessageFor(model => model.FirstName)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.LastName)</td>
            <td>@Html.EditorFor(model => model.LastName)</td>
            <td> @Html.ValidationMessageFor(model => model.LastName)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.Email)</td>
            <td>@Html.EditorFor(model => model.Email)</td>
            <td> @Html.ValidationMessageFor(model => model.Email)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.MobilePhone)</td>
            <td>@Html.EditorFor(model => model.MobilePhone)</td>
            <td>@Html.ValidationMessageFor(model => model.MobilePhone)</td>
        </tr>
        <tr>
            <td><input type="submit" value="Сохранить" /> </td>
            <td></td>
        </tr>
    </table>
}
<h4>Любимые исполнители</h4>
<table id="favoriteSingers" border="1" width="300">
    <tr>
        <td>Название</td>
        <td>Жанр</td>
    </tr>
    @if (Model.Singers == null || !Model.Singers.Any())
    {
       
    }
    else
    {




        foreach (var singer in Model.Singers)
        {
            @Html.Partial("SingerEditView", singer)
        }

    }
</table>

<p>Добавьте нового любимого исполнителя</p>
@Html.DropDownList("Genre", Model.Genres, "Жанр", new { onchange = @"Change()" })
@Html.DropDownList("Singers", new SelectList(string.Empty, "Value", "Text"), "Исполнитель")
<a href="#" id="add" style="display: none" onclick="addSinger()">Добавить</a>
<br/>
<a href="#" onclick="AddNewSinger()">Создать нового исполнителя и добавить к избранному</a>



<script type="text/javascript">
    function removeSinger(id) {

        $.ajax({
            url: '/home/removefavoritesinger/' + id,
            type: 'get',
            success: removeSingerOnClient(id),
            error: alertOnError
        });
    }

    function addSinger() {
        var id = $('#Singers :selected').val();
        $.ajax({
            url: '/home/addfavoritesinger/' + id,
            type: 'get',
            success: function (data) {
                AddSingerOnClient(data);
            },
            error: alertOnError
        });
    }



    function AddSingerOnClient(data) {
        $("#favoriteSingers").append(data);
    }


    function removeSingerOnClient(iden) {
        $("#" + iden).remove();
    }

    function alertOnError() {
        alert("Запроса к серверу завершился неудачей");
    }

    function Change() {
        $("#Singers").empty();
        var data = $("#Genre").val();
        if (data !== "")
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetByGenre", "Singer")',

                dataType: 'json',

                data: { genreId: data },
                success: function (singers) {
                    if (singers.length !== 0)
                        $("#add").show();
                    else
                        $("#add").hide();
                    $.each(singers, function (i, state) {
                        $("#Singers").append('<option value="' + state.SingerId + '">' +
                            state.Name + '</option>');


                    });
                },
                error: function (ex) {
                    $("#add").hide();
                    alert('Failed to retrieve states.' + ex);
                }
            });
        else {
            $("#add").hide();
            $("#Singers").append('<option>Исполнитель</option>');
        }

        return false;
    }

    function AddNewSinger() {

        $.ajax({
            url: '/Singer/AddNewFavoriteSinger',
            type: 'get',
            success: function (data) {
                AddSingerOnClient(data);
            },
            error: alertOnError
        });
    }

    function SaveAndAddNewSinger(id) {
        $.ajax({
            url: '/Singer/CreateNewSinger',
            type: 'POST',
            data: {
                name: $('#' + id).find('#Name').val(),
                genreId: $('#' + id).find('#ddl :selected').val()
            },
            success: function (data) {
                $('#' + id).remove();
                $.ajax({
                    type: 'POST',
                    url: '/home/addfavoritesinger/' + data.SingerId,
                    success: function (data1) {
                        AddSingerOnClient(data1);
                    },
                    error: alertOnError
                });



            },
            error: alertOnError
        });

    }






</script>

WebApplication2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

WebApplication2/Views/Home/View.cshtml
@model WebApplication2.Models.UserInfoViewModel

@{
    ViewBag.Title = "Edit User";
}

<h2>View</h2>

WebApplication2/Views/Home/ViewUser.cshtml
@model WebApplication2.Models.UserInfoModel

@{
    ViewBag.Title = "Просмотр пользователя";
}

<h2>Пользователь</h2>
@if (Model == null)
{
    <p>Информация о пользователе недоступа, нажмите кнопку редактировать для заполнения информации.</p>
}
else
{
    <table>
        <tr>
            <td>   @Html.DisplayNameFor(model => model.FirstName)</td>
            <td>@Html.DisplayFor(model => model.FirstName)</td>
        </tr>
        <tr>
            <td>   @Html.DisplayNameFor(model => model.LastName)</td>
            <td>@Html.DisplayFor(model => model.LastName)</td>
        </tr>
        <tr>
            <td>   @Html.DisplayNameFor(model => model.Email)</td>
            <td>@Html.DisplayFor(model => model.Email)</td>
        </tr>
        <tr>
            <td>   @Html.DisplayNameFor(model => model.MobilePhone)</td>
            <td>@Html.DisplayFor(model => model.MobilePhone)</td>
        </tr>
    </table>

    if (Model.Singers == null || !Model.Singers.Any())
    {
        <p>Нет любимых исполнителей</p>
    }
    else
    {
        <h4>Любимые исполнители</h4>
        <table>
            <tr>
                <td>Название</td>
                <td>Жанр</td>
            </tr>

            @foreach (var singer in Model.Singers)
            {
                @Html.Partial("SingerView",singer)
            }
        </table>
    }

}    
@Html.ActionLink("Редактировать", "EditUser", "Home")